environment: development

crossbar:
    host: 0.0.0.0
    port: 9999
    realm: rosetta

slack:
    token: # Your Slack Bot Token here...

redis:
    host: localhost
    port: 6379
    databases:
        main: 0

# Command configurations

slap:
    - $SOURCEUSER$ slaps $TARGETUSER$ around with a large trout.
    - $SOURCEUSER$ slaps $TARGETUSER$ around with a large :$EMOJI$:.